spring:
  application:
   name: EmployeeJSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
   
server:
  port: 2000
  servlet:
    context-path: /mvc
    
logging:
  level:
    web: DEBUG